### ISSUE TITLE
Security issue of the tool 

### ISSUE THREAD

**Issue by PhantomDave** [cyberpeppe/instatool#1]
There is a security issue in this tool because I don't see any kind of deletion or hashing of the password saved in the file, can you just double check that? 

Also, this is not related but it is customary to use English in the code

Take it as constructive criticism, not whining please ❤️

**Comment by cyberpeppe** [comment]
Hi Dave! Thanks for reporting this. The secret.txt file is stored locally, it automatically resets every time you start the script.

**Comment by cyberpeppe** [comment]
For the english tool, I will work on it in the next few days

**Comment by cyberpeppe** [comment]
I updated the python code, which now encrypts the password and saves it encrypted
